services:
  # L'application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yield-ai-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - yield-network
      - python-network # <--- Ajout du réseau IA ici
    depends_on:
      - db

  # La base de données MySQL
  db:
    image: mysql:8.0
    container_name: yield-ai-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yield_ai
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yield-network

networks:
  yield-network:
    driver: bridge
  # Connexion au réseau existant du serveur Python
  python-network:
    external: true
    name: yield_ai_service_yield_bridge # <--- Ton nom de réseau trouvé via docker network ls

volumes:
  dbdata:
